version: '3'

env:
  IMAGE: jswank/python-cdk
  TAG: latest

tasks:
  default:
    cmds:
      - task: build
  build:
    desc: build a new image
    cmd: podman build -t ${IMAGE}:${TAG} {{.CLI_ARGS}} -f Dockerfile ctx
  publish:
    desc: publish the image
    cmds:
      - podman tag ${IMAGE}:${TAG} ${REGISTRY}/${IMAGE}:${TAG}
      - echo "${{.REGISTRY_PASS_VAR}}" | podman login ${REGISTRY} -u ${REGISTRY_USER} --password-stdin
      - podman push ${REGISTRY}/${IMAGE}:${TAG}
      - podman  logout ${REGISTRY}
    env:
      REGISTRY: ghcr.io
      REGISTRY_USER: jswank
      REGISTRY_PASS_VAR: REGISTRY_PASSWORD # this environment variable will be passed to podman login as the password
